from __future__ import annotations

import importlib.util
import io
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path


SCRIPT = Path(__file__).parents[1] / "scripts" / "validate_deliverable.py"
SPEC = importlib.util.spec_from_file_location("validate_deliverable", SCRIPT)
assert SPEC and SPEC.loader
VALIDATOR = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = VALIDATOR
SPEC.loader.exec_module(VALIDATOR)


class DeliverableValidatorTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)

    def validate(
        self,
        path: Path,
        *,
        allowed_extensions: set[str] | None = None,
        require_flat_archive: bool = False,
    ) -> dict[str, object]:
        validator = VALIDATOR.DeliverableValidator(
            allowed_extensions=allowed_extensions or set(),
            require_flat_archive=require_flat_archive,
        )
        return validator.validate([path])

    def test_clean_professional_gap_language_passes(self) -> None:
        document = self.root / "Control Assessment.md"
        document.write_text(
            "# Control Assessment\n\n"
            "Available records do not establish the account-review cadence.\n",
            encoding="utf-8",
        )

        report = self.validate(document)

        self.assertTrue(report["ok"])
        self.assertEqual(report["findings"], [])

    def test_ai_and_review_workflow_labels_fail(self) -> None:
        document = self.root / "assessment.md"
        document.write_text(
            "Generated by Codex.\nStatus: draft_for_human_review\n",
            encoding="utf-8",
        )

        report = self.validate(document)
        codes = {item["code"] for item in report["findings"]}

        self.assertFalse(report["ok"])
        self.assertIn("ai_provenance", codes)
        self.assertIn("review_workflow_label", codes)

    def test_common_template_variables_fail(self) -> None:
        document = self.root / "policy.md"
        document.write_text(
            "# [Program Name]\n"
            "Owner: {{ PROGRAM_OWNER }}\n"
            "Date: ${EFFECTIVE_DATE}\n"
            "Scope: TBD\n",
            encoding="utf-8",
        )

        report = self.validate(document)
        codes = {item["code"] for item in report["findings"]}

        self.assertFalse(report["ok"])
        self.assertIn("unresolved_placeholder", codes)
        self.assertIn("template_expression", codes)
        self.assertIn("unfinished_marker", codes)

    def test_docx_xml_and_core_properties_are_scanned(self) -> None:
        document = self.root / "assessment.docx"
        with zipfile.ZipFile(document, "w") as archive:
            archive.writestr(
                "word/document.xml",
                '<?xml version="1.0"?>'
                '<document><body><p><t>[Control ID]</t></p></body></document>',
            )
            archive.writestr(
                "docProps/core.xml",
                '<?xml version="1.0"?>'
                "<properties><creator>AI-generated</creator></properties>",
            )

        report = self.validate(document)
        codes = {item["code"] for item in report["findings"]}

        self.assertFalse(report["ok"])
        self.assertIn("unresolved_placeholder", codes)
        self.assertIn("ai_provenance", codes)

    def test_archive_allowlist_and_flatness_are_enforced(self) -> None:
        archive_path = self.root / "Submission.zip"
        with zipfile.ZipFile(archive_path, "w") as archive:
            archive.writestr("nested/assessment.pdf", b"%PDF placeholder")
            archive.writestr("manifest.json", b'{"status":"unsubmitted"}')

        report = self.validate(
            archive_path,
            allowed_extensions={".pdf"},
            require_flat_archive=True,
        )
        codes = {item["code"] for item in report["findings"]}

        self.assertFalse(report["ok"])
        self.assertIn("nested_archive_entry", codes)
        self.assertIn("unexpected_file_type", codes)

    def test_archive_parent_relative_path_fails(self) -> None:
        archive_path = self.root / "Submission.zip"
        with zipfile.ZipFile(archive_path, "w") as archive:
            archive.writestr("../assessment.txt", b"Assessment content.")

        report = self.validate(archive_path)

        self.assertFalse(report["ok"])
        self.assertIn(
            "unsafe_archive_path",
            {item["code"] for item in report["findings"]},
        )

    def test_legacy_sidecar_process_fields_fail(self) -> None:
        sidecar = self.root / "assessment.json"
        sidecar.write_text(
            '{"status":"unsubmitted","reviewer_actions":["Approve"]}',
            encoding="utf-8",
        )

        report = self.validate(sidecar)

        self.assertFalse(report["ok"])
        self.assertIn(
            "internal_process_metadata",
            {item["code"] for item in report["findings"]},
        )

    def test_presentation_filename_fails(self) -> None:
        document = self.root / "policy-draft.txt"
        document.write_text("Policy content.\n", encoding="utf-8")

        report = self.validate(document)

        self.assertFalse(report["ok"])
        self.assertIn(
            "presentation_filename",
            {item["code"] for item in report["findings"]},
        )

    def test_ooxml_helper_accepts_valid_archive_bytes(self) -> None:
        payload = io.BytesIO()
        with zipfile.ZipFile(payload, "w") as archive:
            archive.writestr(
                "xl/sharedStrings.xml",
                '<?xml version="1.0"?><sst><si><t>Completed</t></si></sst>',
            )
        workbook = self.root / "workbook.xlsx"
        workbook.write_bytes(payload.getvalue())

        report = self.validate(workbook)

        self.assertTrue(report["ok"])


if __name__ == "__main__":
    unittest.main()
